export const CHANGE_STYLE_MODE= 'CHANGE_STYLE_MODE'

export const CHANGE_OPTIONS = 'CHANGE_OPTIONS'
export const ADD_ARTICLE_LIST = 'ADD_ARTICLE_LIST'
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'

export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_INDEX_IMG_REQUEST = 'GET_INDEX_IMG_REQUEST'
export const GET_INDEX_IMG_SUCCESS = 'GET_INDEX_IMG_SUCCESS'
export const GET_INDEX_IMG_FAILURE = 'GET_INDEX_IMG_FAILURE'

export const ARTICLE_LIST = 'ARTICLE_LIST'
export const ARTICLE_LIST_REQUEST = 'ARTICLE_LIST_REQUEST'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
export const ARTICLE_LIST_FAILURE = 'ARTICLE_LIST_FAILURE'

export const ARTICLE_DETAIL = 'ARTICLE_DETAIL'
export const ARTICLE_DETAIL_REQUEST = 'ARTICLE_DETAIL_REQUEST'
export const ARTICLE_DETAIL_SUCCESS = 'ARTICLE_DETAIL_SUCCESS'
export const ARTICLE_DETAIL_FAILURE = 'ARTICLE_DETAIL_FAILURE'

export const COMMENT_LIST = 'COMMENT_LIST'
export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS'
export const COMMENT_LIST_FAILURE = 'COMMENT_LIST_FAILURE'

export const TOGGLE_LIKE = 'TOGGLE_LIKE'
export const TOGGLE_LIKE_REQUEST = 'TOGGLE_LIKE_REQUEST'
export const TOGGLE_LIKE_SUCCESS = 'TOGGLE_LIKE_SUCCESS'
export const TOGGLE_LIKE_FAILURE = 'TOGGLE_LIKE_FAILURE'

export const PRENEXT_ARTICLE = 'PRENEXT_ARTICLE'
export const PRENEXT_ARTICLE_REQUEST = 'PRENEXT_ARTICLE_REQUEST'
export const PRENEXT_ARTICLE_SUCCESS = 'PRENEXT_ARTICLE_SUCCESS'
export const PRENEXT_ARTICLE_FAILURE = 'PRENEXT_ARTICLE_FAILURE'

export const TAG_LIST = 'TAG_LIST'
export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCESS = 'TAG_LIST_SUCCESS'
export const TAG_LIST_FAILURE = 'TAG_LIST_FAILURE'

export const GET_APPS = 'GET_APPS'
export const GET_APPS_SUCCESS = 'GET_APPS_SUCCESS'
export const GET_APPS_FAILURE = 'GET_APPS_FAILURE'
export const GET_APPS_REQUEST = 'GET_APPS_REQUEST'

export const GET_SNSLOGINS = 'GET_SNSLOGINS'
export const GET_SNSLOGINS_SUCCESS = 'GET_SNSLOGINS_SUCCESS'
export const GET_SNSLOGINS_FAILURE = 'GET_SNSLOGINS_FAILURE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'